config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "letters#index"
  get 'pages/home'
  resources :letters
  resources :grades, only: [:index, :new, :create, :edit, :update]
  resources :kids,except:[:destroy] do
    resources :growths, only: [:index, :new, :create, :edit, :update]
  end
  resources :growths do
     collection {post :import}
     collection {get :export}
  end
  resources :users, only: [:index, :update, :show] do
    collection {post :admit}
  end
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :kids

  with_options presence: true do
    validates :age,  format: { with: /\A\d{1}\z/, message: 'input only 1 digit' }
    validates :name, uniqueness: { case_sensitive: false }
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :authenticate_user!
  before_action :nursery_user!
  before_action :set_grades, only: [:index, :new, :create, :edit, :update]

  def index
  end

  def new
    @grade = Grade.new
  end

  def create
    @grade = Grade.new(grade_params)
    if @grade.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @grade = Grade.find(params[:id])
  end

  def update
    @grade = Grade.find(params[:id])
    if @grade.update(grade_params)
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  private

  def nursery_user!
    redirect_to root_path if current_user.authority_id != 3
  end

  def grade_params
    params.require(:grade).permit(:age, :name)
  end

  def set_grades
    @grades = Grade.order(age: 'ASC')
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/edit.html.erb
<%= render partial: "shared/nursery_menu.erb" %>

<div class="wrapper">

  <div class="back_errors">
    <%= render 'shared/error_messages', resource: @grade %>
  </div>
  
  <%= render partial: "shared/grade_show.erb",lovals:{ grade: @grade } %>

  <%= render partial: "shared/grade_form" ,locals:{ grade: @grade}%>

</div>

app/views/grades/index.html.erb
<%= render partial: "shared/nursery_menu.erb" %>

<div class="wrapper">

  <%= render partial: "shared/grade_show.erb"  %>

    <br/>
    <%= link_to 'クラスを新しく登録する', new_grade_path %>
</div>

app/views/grades/new.html.erb
<%= render partial: "shared/nursery_menu.erb" %>

<div class="wrapper">

  <div class="back">
    <%= render 'shared/error_messages', resource: @grade %>
  </div>

  <%= render partial: "shared/grade_show.erb"  %>
  
  <%= render partial: "shared/grade_form" ,locals:{ grade: @grade}%>

</div>