config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "letters#index"
  get 'pages/home'
  resources :letters
  resources :grades, only: [:index, :new, :create, :edit, :update]
  resources :kids,except:[:destroy] do
    resources :growths, only: [:index, :new, :create, :edit, :update]
  end
  resources :growths do
     collection {post :import}
     collection {get :export}
  end
  resources :users, only: [:index, :update, :show] do
    collection {post :admit}
  end
end

app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :grade
  belongs_to :user
  has_many :growths

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender

  with_options presence: true do
    validates :name
    validates :birth_date
    validates :gender_id, numericality: { other_than: 1, message: "can't be blank" }, allow_blank: true
    validates :start_month, format: { with: /\A\d{4}年\d{2}月\z/, message: 'input correctly' }
  end

  validates :end_month, format: { with: /\A\d{4}年\d{2}月\z/, message: 'input correctly' }, allow_blank: true
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :authenticate_user!
  before_action :nursery_user!, except: [:show]
  before_action :set_kids, only: [:index]

  def index
  end

  def new
    @kid = Kid.new(start_month: Date.today.next_month(1).strftime('%Y年%m月').to_s)
  end

  def create
    @kid = Kid.new(kid_params)
    if @kid.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @kid = Kid.find(params[:id])
  end

  def update
    @kid = Kid.find(params[:id])
    if @kid.update(kid_params)
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @kid = Kid.find(params[:id])
    @kid.destroy
    redirect_to action: 'index'
  end

  def show
    if nursery_user?
      @kid = Kid.find(params[:id])
      @growths = Growth.where(kid_id: params[:id]).order(inspection_date: :desc)
    elsif users_kid?
      @growths = Growth.where(kid_id: params[:id]).order(inspection_date: :desc)
    else
      redirect_to user_path(id: current_user.id)
    end
  end

  private

  def nursery_user!
    redirect_to root_path if current_user.authority_id != 3
  end

  def nursery_user?
    current_user.authority_id == 3
  end

  def set_kids
    case current_user.authority_id
    when 2, 4
      @kids = Kid.where(user_id: current_user.id)
    when 3
      @kids = Kid.order(birth_date: :desc)
    else
      redirect_to root_path
    end
  end

  def users_kid?
    @kid = Kid.find(params[:id])
    @kid.user_id == current_user.id
  end

  def kid_params
    params.require(:kid).permit(
      :name, :birth_date, :gender_id, :start_month, :end_month, :grade_id, :user_id
    )
  end
end

app/helpers/kids_helper.rb
module KidsHelper
  attr_accessor :age, :age_in_month

  # 年齢と月齢を設定する
  def cal_age_in_month(kid)
    reference_date = Date.today

    today_m = reference_date.year * 12 + reference_date.month
    birth_date_m = kid.birth_date.year * 12 + kid.birth_date.month
    month = today_m - birth_date_m

    month -= 1 if reference_date.mday < kid.birth_date.mday

    @age = (month / 12).floor
    @age_in_month = month % 12
  end
end

app/views/kids/edit.html.erb
<div class="wrapper">

  <%= render 'shared/error_messages', resource: @kid %>

  <h2>園児の変更</h2>

  <%= render partial: "shared/kid_form", locals:{ kid: @kid}  %>

</div>

app/views/kids/index.html.erb
<%= render partial: "shared/nursery_menu.erb" %>

<div class="wrapper">
  <% if current_user.authority_id == 3%>
    <%= link_to '園児を新しく登録する', new_kid_path %>
  <% end %>
 
  <ul class="kid_lists">
    <% @kids.each do |kid| %>
    <%= render partial: "shared/kid_show.erb" ,locals: {kid: kid} %>
    </li>
  <% end %>
  </ul>


    <br/>

  <% if current_user.authority_id == 3%>
    <%= link_to '園児を新しく登録する', new_kid_path %>
  <% end %>

</div>

app/views/kids/new.html.erb
<div class="wrapper">

  <%= render 'shared/error_messages', resource: @kid %>

  <h2>園児の登録</h2>

  <%= render partial: "shared/kid_form", locals:{ kid: @kid}  %>

</div>

app/views/kids/show.html.erb
<%= render partial: "shared/nursery_menu.erb" %>

<div class="wrapper">
  <ul class="kid_lists">
  <%= render partial: "shared/kid_show.erb",locals: {kid: @kid}  %>
  </ul>

<%= render partial: "shared/growth_show.erb",locals: {growths: @growths} %>

    <br/>

  <% if current_user.authority_id == 3%>
    <%= link_to '身長測定データを新しく登録する', new_kid_growth_path(kid_id: @kid.id) %>
  <% end %>

</div>