config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "letters#index"
  get 'pages/home'
  resources :letters
  resources :grades, only: [:index, :new, :create, :edit, :update]
  resources :kids,except:[:destroy] do
    resources :growths, only: [:index, :new, :create, :edit, :update]
  end
  resources :growths do
     collection {post :import}
     collection {get :export}
  end
  resources :users, only: [:index, :update, :show] do
    collection {post :admit}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authority.rb
class Authority < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '保護者' },
    { id: 3, name: '保育士' },
    { id: 4, name: '卒園児保護者' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :class
  belongs_to :user

  with_options presence: true do
    validates :name
    validates :birth_date
    validates :gender_id
    validates :start_month
    validates :class_id
    validates :user_id
  end
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '男' },
    { id: 3, name: '女' }
  ]

  include ActiveHash::Associations
  has_many :kids
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'おたより' },
    { id: 3, name: '献立表' },
    { id: 4, name: '大切なおしらせ' }
  ]

  include ActiveHash::Associations
  has_many :letters
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :kids

  with_options presence: true do
    validates :age,  format: { with: /\A\d{1}\z/, message: 'input only 1 digit' }
    validates :name, uniqueness: { case_sensitive: false }
  end
end

app/models/growth.rb
class Growth < ApplicationRecord
  belongs_to :kid

  with_options presence: true do
    validates :month
    validates :inspection_date
    validates :weight
    validates :height
    validates :kid_id
  end

  validates :weight, numericality: { greater_than: 2, message: '体重は2kgより大きい値を登録してください', allow_nil: true }
  validates :weight, numericality: { less_than: 30, message: '体重は30kgより小さい値を登録してください', allow_nil: true }

  validates :height, numericality: { greater_than: 40, message: '身長は40cmより大きい値を登録してください', allow_nil: true }
  validates :height, numericality: { less_than: 200, message: '身長は200cmより小さい値を登録してください', allow_nil: true }

  def self.import(file)
    column_names = [:kid_id, :kid_name, :kid_birth_date, :month, :inspection_date, :height, :weight]
    slice_column = [:kid_id, :month, :inspection_date, :height, :weight]

    CSV.foreach(file.path, headers: column_names) do |row|
      growth = Growth.new(row.to_hash.slice(*slice_column))
      growth.save if growth.valid?
    end
  end
end

app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :grade
  belongs_to :user
  has_many :growths

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender

  with_options presence: true do
    validates :name
    validates :birth_date
    validates :gender_id, numericality: { other_than: 1, message: "can't be blank" }, allow_blank: true
    validates :start_month, format: { with: /\A\d{4}年\d{2}月\z/, message: 'input correctly' }
  end

  validates :end_month, format: { with: /\A\d{4}年\d{2}月\z/, message: 'input correctly' }, allow_blank: true
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :user
  has_one_attached :pdf_file

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  with_options presence: true do
    validates :title
    validates :genre_id, numericality: { other_than: 1, message: "can't be blank", allow_blank: true }
    validates :pdf_file
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :letters
  has_many :kids

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :authority

  with_options presence: true do
    validates :name
    validates :authority_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :postal_code, format: { with: /\A\d{7}\z/, allow_blank: true }
    validates :pref
    validates :city
    validates :town
    validates :phone_number, length: { within: 10..11 },
                             format: { with: /\A\d{10,11}\z/, message: 'input only number' }
  end
end

app/models/users_child.rb
class UsersChild < ApplicationRecord
  belongs_to :child_class
  belongs_to :user


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender

  with_options presence: true do
    validates :name
    validates :birth_date
    validates :gender_id
    validates :start_month
    validates :child_class
    validates :user
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :authenticate_user!
  before_action :nursery_user!, except: [:show]
  before_action :set_kids, only: [:index]

  def index
  end

  def new
    @kid = Kid.new(start_month: Date.today.next_month(1).strftime('%Y年%m月').to_s)
  end

  def create
    @kid = Kid.new(kid_params)
    if @kid.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @kid = Kid.find(params[:id])
  end

  def update
    @kid = Kid.find(params[:id])
    if @kid.update(kid_params)
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @kid = Kid.find(params[:id])
    @kid.destroy
    redirect_to action: 'index'
  end

  def show
    if nursery_user?
      @kid = Kid.find(params[:id])
      @growths = Growth.where(kid_id: params[:id]).order(inspection_date: :desc)
    elsif users_kid?
      @growths = Growth.where(kid_id: params[:id]).order(inspection_date: :desc)
    else
      redirect_to user_path(id: current_user.id)
    end
  end

  private

  def nursery_user!
    redirect_to root_path if current_user.authority_id != 3
  end

  def nursery_user?
    current_user.authority_id == 3
  end

  def set_kids
    case current_user.authority_id
    when 2, 4
      @kids = Kid.where(user_id: current_user.id)
    when 3
      @kids = Kid.order(birth_date: :desc)
    else
      redirect_to root_path
    end
  end

  def users_kid?
    @kid = Kid.find(params[:id])
    @kid.user_id == current_user.id
  end

  def kid_params
    params.require(:kid).permit(
      :name, :birth_date, :gender_id, :start_month, :end_month, :grade_id, :user_id
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/growths_helper.rb
module GrowthsHelper
end

app/helpers/kids_helper.rb
module KidsHelper
  attr_accessor :age, :age_in_month

  # 年齢と月齢を設定する
  def cal_age_in_month(kid)
    reference_date = Date.today

    today_m = reference_date.year * 12 + reference_date.month
    birth_date_m = kid.birth_date.year * 12 + kid.birth_date.month
    month = today_m - birth_date_m

    month -= 1 if reference_date.mday < kid.birth_date.mday

    @age = (month / 12).floor
    @age_in_month = month % 12
  end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TsumikiNote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag('favicon.ico') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://postcode-jp.com/js/postcodejp.js" charset="utf-8"> </script>
  </head>

  <body>
    <%= render "shared/header"%>

    <div class="wrapper_back">
      <%= yield %>
    </div>

    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper">

  <div class="navigation mobile" style="display: block;">
    <div class="home_navi">
      <ul class="navi_menu_list">
        <li class="navi_menu">
          <%= link_to "新着情報", "#new_news", class: "navi_menu_a" %>
        </li>
        <li class="navi_menu">
          <%= link_to "Oe nursery schoolについて", "#about", class: "navi_menu_a" %>
        </li>
        <li class="navi_menu">
          <%= link_to "園での生活", "#life", class: "navi_menu_a" %>
        </li>
        <li class="navi_menu">
          <%= link_to "お問合せ", "#contact", class: "navi_menu_a" %>
        </li>
    </div>
  </div>

  <div class="picture">
    <img src="/assets/24059769_s.jpg", class="kid_picture", alt="" >
    <img src="/assets/animal_flame.png", class="animal_picture", alt="" >
  </div>

  <section class="content_fullwidth_padded" id="new_news">
      <div class="title_grid_full">
        <h2 class="home_h2">新着情報</h2>
      </div>
        <hr class="hr1">
      
    <h3>2022/09/30 Oe nursery schoolの一時保育について</h3>
    <h3>2022/09/30 保護者用ログインページのご案内</h3>

  </section>
  <section class="content_fullwidth_padded" id="about">
      <div class="title_grid_full">
        <h2 class="home_h2">Oe nursery schoolについて</h2>
      </div>
        <hr class="hr1">
      
    <h3 class="home_h3">ごあいさつ</h3>
      <p class="greeting">
      Tsumiki-noteへアクセスいただき、ありがとうございます。<br>
      本アプリケーションは、大江真未子のポートフォリオとして作成しました。<br>
      保育士と保護者の連絡をスムーズに取り合うことで、
      保育の時間や家庭での時間をより充実したものにして欲しいという願いを込めています。<br>
      ぜひ、ご覧くださいませ。
      </p>

    <h3 class="home_h3">テスト用アカウントのご紹介</h3>
      <p class="test_account">

      ログイン<br>
      保育士アカウント<br>
      E-mail: test1@test.com<br>
      Password: 000000y<br>
<br>
      保護者アカウント<br>
      E-mail: test4@test.com<br>
      Password: 000000y
      </p>



  </section>
  <section class="content_fullwidth_padded" id="life">
      <div class="title_grid_full">
        <h2 class="home_h2">園での生活</h2>
      </div>
        <hr class="hr1">

    <h3 class="home_h3">保育方針</h3>
    <p class="orgin_policy">
      子供たちの主体性を大事に発言・行動・思いを尊重する。
    </p>
      
    <h3 class="home_h3">1日の流れ</h3>
      <br>

    <h3 class="home_h3">年間行事</h3>
      <br>


  </section>



  <section class="content_fullwidth_padded" id="contact">
      <div class="title_grid_full">
        <h2 class="home_h2">お問合せ</h2>
      </div>
        <hr class="hr1">
      <p class="contact_details">
      大江　真未子　oe.mamiko20200404@gmail.com
      </p>

  </section>

</div>

app/views/shared/_child_form.erb
  <div class="child_lists">

    <%= form_with(model: @users_child, local: true, class:'new_child' ) do |f| %>

      <div class="child_field">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </div>

      <div class="child_field">
         <label class="form-text">生年月日</label>
         <%= raw sprintf(
                     f.date_select(
                       :birth_date,
                       class:'select-birth',
                       id:"birth-date",
                       use_month_numbers: true,
                       prompt:'--',
                       start_year: (Time.now.year - 10),
                       end_year: (Time.now.year ),
                       date_separator: '%s'),
                     "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>

      <div class="child_field">
        入園月を入力して下さい。yyyy年mm月→ yyyymm<br/>
        <%= f.label :start_month %>
        <%= f.text_field :start_month ,placeholder: "yyyymm" %>
      </div>

      <div class="child_field">
        性別を選んで下さい<br/>
        <%= f.label :gender_id %>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"gender-category"}) %>
      </div>

      <div class="child_field">
        <%= f.label :child_class_id %>
        <%= f.collection_select(:child_class_id, ChildClass.all, :id, :class_name, {}, {class:"select-box", id:"choice_class"}) %>
      </div>

      <div class="child_field">
        <%= f.label :user_id %>
        <%= f.collection_select(:user_id, User.all, :id, :name, {},{class:"select-box", id:"choice_user"}) %>
      </div>

      <div class="child_field">
        <%= f.submit "登録する" , class:"btn" %>
      </div>

    <% end %>
  </div>
  <div class="back_link">
    <%= link_to '戻る', child_classes_path, class:"back-btn"  %>
  </div>

app/views/shared/_error_messages.erb
<% if resource.errors.any? %>
<div class="error-alert">
  <ul>
    <% resource.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.erb
<div class='footer'>
  <p class='copyright'>Copyright &copy; 2022 Oe Nursery School</p>
</div>

app/views/shared/_grade_form.erb
  <div class="kid_class_lists">

    <%= form_with(model: @grade, local: true, class:'new_grade' ) do |f| %>

      <div class="grade_field">
        <%= f.label :age %>
        <%= f.text_field :age, autofocus: true %>才児クラス
      </div>

      <div class="grade_field">
        <%= f.label :name %>
        <%= f.text_field :name %>組さん
      </div>

      <div class="grade_field">
        <%= f.submit "登録する" , class:"btn" %>
      </div>

    <% end %>
  </div>
  <div class="back_link">
    <%= link_to '戻る', grades_path, class:"back-btn"  %>
  </div>

app/views/shared/_grade_show.erb
  <div class="grade_lists">
    <ul>
    <% @grades.each do |grade| %>
      <li>
        <div class="grade_list_age"><%= grade.age %>才児クラス</div>
        <div class="grade_list_name"><%= grade.name %>組さん</div>
        <%= link_to "変更", edit_grade_path(grade.id), class: "btn_edit" %>
      </li>
    <% end %>
    </ul>
  </div>

app/views/shared/_growth_form.erb
  <div class="growth_lists">

      <div class="growth_field">
        名前を確認してください<br/>
        <%= kid.name %>
      </div>

    <%= form_with(model: [@kid, @growth], local: true, class:'new_growth' ) do |f| %>

      <div class="growth_field">
        <%= f.label(:month, "測定月：") %>
        <%= f.text_field :month ,placeholder: "yyyymm" %>
      </div>

      <div class="growth_field">
        <%= f.label(:inspection_date, "測定日：") %>
        <%= f.date_field :inspection_date %>
      </div>

      <div class="growth_field">
        <%= f.label(:weight, "体重：") %>
        <%= f.text_field :weight %> kg
      </div>

      <div class="growth_field">
        <%= f.label(:height, "身長：") %>
        <%= f.text_field :height %> cm
      </div>

      <div class="growth_field">
        <%= f.submit "登録する" , class:"btn" %>
      </div>

    <% end %>
  </div>
  <div class="back_link">
    <%= link_to '戻る', kid_path(id: @kid.id), class:"back-btn"  %>
  </div>

app/views/shared/_growth_show.erb
  <ul class="growth_lists">
    <% growths.each do |growth| %>
    <li class="growth_list">

      <div class="growth_list_inspection_date">
        <%= growth.inspection_date %>
      </div>

      <div class="growth_list_weight">
        <%= growth.weight %> kg
      </div>

      <div class="growth_list_height">
        <%= growth.height %> cm
      </div>


      <% if current_user.authority_id == 3%>
        <%= link_to "変更", edit_kid_growth_path(kid_id: growth.kid_id, id: growth.id), class: "btn_edit" %>
      <% end %>

    </li>
    <%end%>
  </ul>

app/views/shared/_kid_form.erb
  <div class="kid_lists">

    <%= form_with(model: @kid, local: true, class:'new_kid' ) do |f| %>

      <div class="kid_field">
        <%= f.label(:name, "名前") %><br/>
        <%= f.text_field :name, autofocus: true %>
      </div>

      <div class="kid-date-field">
         <label class="form-text">生年月日</label>
         <%= raw sprintf(
                     f.date_select(
                       :birth_date,
                       class:'select-birth',
                       id:"birth-date",
                       use_month_numbers: true,
                       prompt:'--',
                       start_year: (Time.now.year - 10),
                       end_year: (Time.now.year ),
                       date_separator: '%s'),
                     "<p class:'date-field'> 年 </p>", "<p class:'date-field'> 月 </p>") + "<p class:'date-field'> 日 </p>" %>
      </div>

      <div class="kid_field">
        <%= f.label(:start_month, "入園月を入力して下さい。") %><br />
        <%= f.text_field :start_month ,placeholder: "yyyy年mm月" %>
      </div>

      <% if params[:action]=="edit" %>

      <div class="kid_field">
        <%= f.label(:end_month, "退園月を入力してください") %><br/>
        <%= f.text_field :end_month ,placeholder: "yyyy年mm月" %>
      </div>

      <% end %>

      <div class="kid_field">
        <%= f.label(:gender_id, "性別") %>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"gender-category"}) %>
      </div>

      <div class="kid_field">
        <%= f.label(:grade_id, "クラス") %>
        <%= f.collection_select(:grade_id, Grade.all, :id, :name, {}, {class:"select-box", id:"choice_class"}) %>
      </div>

      <div class="kid_field">
        <%= f.label :user_id %>
        <%= f.collection_select(:user_id, User.all, :id, :name, {},{class:"select-box", id:"choice_user"}) %>
      </div>

      <div class="kid_field">
        <%= f.submit "登録する" , class:"btn" %>
      </div>

    <% end %>
  </div>
  <div class="back_link">
    <%= link_to '戻る', kids_path, class:"back-btn"  %>
  </div>

app/views/shared/_kid_show.erb
    <li class="kid_list">

      <div class="kid_list_top">

        <% if current_user.authority_id == 3%>
          <%= link_to "変更", edit_kid_path(kid.id), class: "btn_edit" %></ br>
        <% end %>


        <div class="kid_list_class">
        クラス：　<%= kid.grade.name %>組さん
        (<%= kid.grade.age %>歳児クラス)
        </div>

        <%= link_to(kid_path(kid.id)) do %>
        <div class="kid_list_name">
        名　前：　<%= kid.name %>
        </div>
        <%end%>

        <div class="kid_list_gender">
        性　別：　<%= kid.gender.name %>
        </div>

      </div>

      <div class="kid_list_bottom">

        <div class="kid_list_birthday">
        誕生日：　<%= kid.birth_date %>
        </div>

        <div class="kid_list_age_in_month">
        <% cal_age_in_month(kid) %>
        月　齢：　<%= "#{age}歳#{age_in_month}か月" %>
        </div>

        <div class="kid_list_user">
        保護者：　<%= kid.user.name %>
        </div>

        <div class="kid_list_start_month">
        入園月：　<%= kid.start_month %>
        <% if kid.end_month.present? %>
        </ br>退園月：　<%= kid.end_month %>
        <% end %>

      </div>

app/views/shared/_letter.erb
<%= form_with(model: @letter, local: true, id: 'new_letter', class: 'new_letter') do |f| %>

  <div class="letter_field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="letter_field">
    <%= f.label :genre_id %>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre-category"}) %>
  </div>

  <div class="letter_field">
    <label class="form-pdf">
      <span class="pdf-file">ファイル</span>
      <%= f.file_field :pdf_file, class: 'hidden' %>
    </label>
  </div>

  <div class="letter_field">
    <%= f.submit "登録する" , class:"btn" %>
  </div>
  
<% end %>

  <div class="letter_field">
    <%=link_to 'もどる', root_path, class:"back-btn" %>
  </div>

app/views/shared/_letter_form.erb
<%= form_with(model: @letter, local: true, id: 'new_letter', class: 'new_letter') do |f| %>

  <div class="letter_field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="letter_field">
    <%= f.label :genre_id %>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre-category"}) %>
  </div>

  <div class="letter_field">
    <label class="form-pdf">
      <span class="pdf-file">ファイル</span>
      <%= f.file_field :pdf_file, class: 'hidden' %>
    </label>
  </div>

  <div class="letter_field">
    <%= f.submit "登録する" , class:"btn" %>
  </div>
  
<% end %>

<div class="letter_field">
  <%=link_to 'もどる', root_path, class:"back-btn" %>
</div>

app/views/shared/_letter_show.erb
<%# おたよりリンク %>

        <li class="letter">
          <%= link_to letter.title  , url_for(letter.pdf_file), target: "_blank" %>
        <%# 保育士の場合は、編集ボタンと %>
        <% if current_user.authority_id == 3 %>
          <%= link_to "変更",edit_letter_path(letter.id), class: "btn_edit" %>
          <%= link_to "削除",letter_path(letter.id), method: :delete, class: "btn_delete" %>
        <% end %>
        </li>

app/views/shared/_nursery_menu.erb
  <% if current_user.authority_id == 3 %>
    <div class="nursery_menu">
      保育園メニュー：
      <%= link_to 'おたより登録', new_letter_path, class: "menu-list" %>
      <%= link_to 'クラス確認', grades_path, class: "menu-list" %>
      <%= link_to '園児確認', kids_path, class: "menu-list" %>
      <%= link_to '身体測定データ登録', growths_path, class: "menu-list"%>
      <%= link_to 'ユーザー確認', users_path,class: "menu-list" %>
      <% if @check == false %>
      <p>未許可のユーザーがいます</p>
      <%end%>
    </div>
  <% end %>

app/views/shared/_user_show.erb
    <li class="user_list">
      <div class="user_list_permission">
        <% if user.permission == false && current_user.authority_id == 3 %>

        <%= link_to '許可する', admit_users_path(id: user.id),method: :post,class:"btn_permit" %>

        <% end %>
      </div>

      <div class="user_list_name">
        名前：　<%= user.name %><br/>
      </div>
      
      <div class="user_list_email">
        E-mail：　<%= user.email %><br/>
      </div>
      
      <% if current_user.authority_id == 3 %>
      <div class="user_list_authority">
        権限：　<%= Authority.find(user.authority_id).name %><br/>
      </div>
      <% end %>

      <div class="user_list_address">
        住所：　〒<%= user.postal_code %>  
        <%= user.pref %><%= user.city %><%= user.town %><%= user.building %>
      </div>
      
      <div class="user_list_phone_number">
        電話番号：　<%= user.phone_number %>
      </div>
    </li>